import type { InstrumentConfig, Note } from './types.ts';

// Full piano range: A0–C8 (midi 21–108, chromatic)
const NATURAL_NOTES: Note[] = [
  { key: 'a/0',  label: 'A0',  midi: 21 },
  { key: 'bb/0', label: 'Bb0', midi: 22, accidental: 'b' },
  { key: 'b/0',  label: 'B0',  midi: 23 },
  { key: 'c/1',  label: 'C1',  midi: 24 },
  { key: 'db/1', label: 'Db1', midi: 25, accidental: 'b' },
  { key: 'd/1',  label: 'D1',  midi: 26 },
  { key: 'eb/1', label: 'Eb1', midi: 27, accidental: 'b' },
  { key: 'e/1',  label: 'E1',  midi: 28 },
  { key: 'f/1',  label: 'F1',  midi: 29 },
  { key: 'f#/1', label: 'F#1', midi: 30, accidental: '#' },
  { key: 'g/1',  label: 'G1',  midi: 31 },
  { key: 'ab/1', label: 'Ab1', midi: 32, accidental: 'b' },
  { key: 'a/1',  label: 'A1',  midi: 33 },
  { key: 'bb/1', label: 'Bb1', midi: 34, accidental: 'b' },
  { key: 'b/1',  label: 'B1',  midi: 35 },
  { key: 'c/2',  label: 'C2',  midi: 36 },
  { key: 'db/2', label: 'Db2', midi: 37, accidental: 'b' },
  { key: 'd/2',  label: 'D2',  midi: 38 },
  { key: 'eb/2', label: 'Eb2', midi: 39, accidental: 'b' },
  { key: 'e/2',  label: 'E2',  midi: 40 },
  { key: 'f/2',  label: 'F2',  midi: 41 },
  { key: 'f#/2', label: 'F#2', midi: 42, accidental: '#' },
  { key: 'g/2',  label: 'G2',  midi: 43 },
  { key: 'ab/2', label: 'Ab2', midi: 44, accidental: 'b' },
  { key: 'a/2',  label: 'A2',  midi: 45 },
  { key: 'bb/2', label: 'Bb2', midi: 46, accidental: 'b' },
  { key: 'b/2',  label: 'B2',  midi: 47 },
  { key: 'c/3',  label: 'C3',  midi: 48 },
  { key: 'db/3', label: 'Db3', midi: 49, accidental: 'b' },
  { key: 'd/3',  label: 'D3',  midi: 50 },
  { key: 'eb/3', label: 'Eb3', midi: 51, accidental: 'b' },
  { key: 'e/3',  label: 'E3',  midi: 52 },
  { key: 'f/3',  label: 'F3',  midi: 53 },
  { key: 'f#/3', label: 'F#3', midi: 54, accidental: '#' },
  { key: 'g/3',  label: 'G3',  midi: 55 },
  { key: 'ab/3', label: 'Ab3', midi: 56, accidental: 'b' },
  { key: 'a/3',  label: 'A3',  midi: 57 },
  { key: 'bb/3', label: 'Bb3', midi: 58, accidental: 'b' },
  { key: 'b/3',  label: 'B3',  midi: 59 },
  { key: 'c/4',  label: 'C4',  midi: 60 },
  { key: 'db/4', label: 'Db4', midi: 61, accidental: 'b' },
  { key: 'd/4',  label: 'D4',  midi: 62 },
  { key: 'eb/4', label: 'Eb4', midi: 63, accidental: 'b' },
  { key: 'e/4',  label: 'E4',  midi: 64 },
  { key: 'f/4',  label: 'F4',  midi: 65 },
  { key: 'f#/4', label: 'F#4', midi: 66, accidental: '#' },
  { key: 'g/4',  label: 'G4',  midi: 67 },
  { key: 'ab/4', label: 'Ab4', midi: 68, accidental: 'b' },
  { key: 'a/4',  label: 'A4',  midi: 69 },
  { key: 'bb/4', label: 'Bb4', midi: 70, accidental: 'b' },
  { key: 'b/4',  label: 'B4',  midi: 71 },
  { key: 'c/5',  label: 'C5',  midi: 72 },
  { key: 'db/5', label: 'Db5', midi: 73, accidental: 'b' },
  { key: 'd/5',  label: 'D5',  midi: 74 },
  { key: 'eb/5', label: 'Eb5', midi: 75, accidental: 'b' },
  { key: 'e/5',  label: 'E5',  midi: 76 },
  { key: 'f/5',  label: 'F5',  midi: 77 },
  { key: 'f#/5', label: 'F#5', midi: 78, accidental: '#' },
  { key: 'g/5',  label: 'G5',  midi: 79 },
  { key: 'ab/5', label: 'Ab5', midi: 80, accidental: 'b' },
  { key: 'a/5',  label: 'A5',  midi: 81 },
  { key: 'bb/5', label: 'Bb5', midi: 82, accidental: 'b' },
  { key: 'b/5',  label: 'B5',  midi: 83 },
  { key: 'c/6',  label: 'C6',  midi: 84 },
  { key: 'db/6', label: 'Db6', midi: 85, accidental: 'b' },
  { key: 'd/6',  label: 'D6',  midi: 86 },
  { key: 'eb/6', label: 'Eb6', midi: 87, accidental: 'b' },
  { key: 'e/6',  label: 'E6',  midi: 88 },
  { key: 'f/6',  label: 'F6',  midi: 89 },
  { key: 'f#/6', label: 'F#6', midi: 90, accidental: '#' },
  { key: 'g/6',  label: 'G6',  midi: 91 },
  { key: 'ab/6', label: 'Ab6', midi: 92, accidental: 'b' },
  { key: 'a/6',  label: 'A6',  midi: 93 },
  { key: 'bb/6', label: 'Bb6', midi: 94, accidental: 'b' },
  { key: 'b/6',  label: 'B6',  midi: 95 },
  { key: 'c/7',  label: 'C7',  midi: 96 },
  { key: 'db/7', label: 'Db7', midi: 97, accidental: 'b' },
  { key: 'd/7',  label: 'D7',  midi: 98 },
  { key: 'eb/7', label: 'Eb7', midi: 99, accidental: 'b' },
  { key: 'e/7',  label: 'E7',  midi: 100 },
  { key: 'f/7',  label: 'F7',  midi: 101 },
  { key: 'f#/7', label: 'F#7', midi: 102, accidental: '#' },
  { key: 'g/7',  label: 'G7',  midi: 103 },
  { key: 'ab/7', label: 'Ab7', midi: 104, accidental: 'b' },
  { key: 'a/7',  label: 'A7',  midi: 105 },
  { key: 'bb/7', label: 'Bb7', midi: 106, accidental: 'b' },
  { key: 'b/7',  label: 'B7',  midi: 107 },
  { key: 'c/8',  label: 'C8',  midi: 108 },
];

// Natural / piano — concert pitch, no transposition, full piano range A0–C8
export const NATURAL: InstrumentConfig = {
  id: 'natural',
  name: 'Natural',
  clef: 'treble',
  transposition: 0,
  notes: NATURAL_NOTES,
};
